package vistas;

import recursos.MetodosGenerales;
import modelos.Gestor_Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class CambioContra_JFrame extends javax.swing.JFrame {

  public CambioContra_JFrame() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  public Image getIconImage() {
    return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo.jpg"));
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jButton_Volver = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    pass_confirmacion = new javax.swing.JPasswordField();
    btn_guardar = new javax.swing.JButton();
    pass_contrasena = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Recuperación de contraseña");
    setIconImage(getIconImage());
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(255, 116, 1));

    jButton_Volver.setBackground(new java.awt.Color(0, 220, 62));
    jButton_Volver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButton_Volver.setForeground(new java.awt.Color(255, 255, 255));
    jButton_Volver.setText("Volver");
    jButton_Volver.setBorder(null);
    jButton_Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton_Volver.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_VolverActionPerformed(evt);
          }
        });

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Nueva contraseña:");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Confirmar contraseña:");

    jLabel3.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("<html>Cambio de contraseña<hr/></html>");

    jLabel4.setBackground(new java.awt.Color(255, 255, 255));
    jLabel4.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/imagenes/Loguitox90.jpg"))); // NOI18N
    jLabel4.setBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 220, 62), 2));

    pass_confirmacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    pass_confirmacion.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            pass_confirmacionActionPerformed(evt);
          }
        });

    btn_guardar.setBackground(new java.awt.Color(0, 220, 62));
    btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
    btn_guardar.setText("Guardar contraseña");
    btn_guardar.setBorder(null);
    btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btn_guardar.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_guardarActionPerformed(evt);
          }
        });

    pass_contrasena.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            pass_contrasenaActionPerformed(evt);
          }
        });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(0, 157, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(153, 153, 153))
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(
                                        jLabel3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(
                                        jButton_Volver,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(
                                                pass_confirmacion,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                250,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                jLabel1,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                jLabel2,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                btn_guardar,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(pass_contrasena))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(
                        jButton_Volver,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        25,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(
                        jLabel3,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        pass_contrasena,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        25,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        pass_confirmacion,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        25,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)
                    .addComponent(
                        btn_guardar,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        30,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                jPanel1,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                jPanel1,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void btn_guardarActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btn_guardarActionPerformed
    String contrasena = pass_contrasena.getText();
    String confirmacion = pass_confirmacion.getText();

    if (!MetodosGenerales.validarContraseña(contrasena)) {
      JOptionPane.showMessageDialog(
          null,
          "Ingrese una contraseña con mayúsculas, minículas, números y carácteres especiales");
    } else {
      if (contrasena.equals(confirmacion)) {
        String correo = Recuperacion_JFrame.getCorreo();
        Gestor_Usuario.cambiarContraseña(correo, contrasena);
        pass_contrasena.setText("");
        pass_confirmacion.setText("");
      } else {
        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
      }
    }
  } // GEN-LAST:event_btn_guardarActionPerformed

  private void jButton_VolverActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton_VolverActionPerformed

    Login_JFrame sesion = new Login_JFrame();
    sesion.setVisible(true);
    this.dispose();
  } // GEN-LAST:event_jButton_VolverActionPerformed

  private void pass_confirmacionActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_pass_confirmacionActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_pass_confirmacionActionPerformed

  private void pass_contrasenaActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_pass_contrasenaActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_pass_contrasenaActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_guardar;
  private javax.swing.JButton jButton_Volver;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPasswordField pass_confirmacion;
  private javax.swing.JPasswordField pass_contrasena;
  // End of variables declaration//GEN-END:variables
}
