package vistas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

import modelos.Gestor_Usuario;
import modelos.Usuario;
import static recursos.MetodosGenerales.abrirVentana;
import recursos.MetodosGenerales;

public class CrearUsr_JFrame extends javax.swing.JFrame {

  public CrearUsr_JFrame() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  @Override
  public Image getIconImage() {
    return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo.jpg"));
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jButton_Volver = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    txt_nombre = new javax.swing.JTextField();
    jButton_Ingresar = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    txt_correo = new javax.swing.JTextField();
    txt_identificacion1 = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    pass_contraseña = new javax.swing.JPasswordField();
    jLabel7 = new javax.swing.JLabel();
    pass_confirmacion = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Creación de usuario");
    setIconImage(getIconImage());
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(255, 116, 1));

    jButton_Volver.setBackground(new java.awt.Color(0, 220, 62));
    jButton_Volver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButton_Volver.setForeground(new java.awt.Color(255, 255, 255));
    jButton_Volver.setText("Volver");
    jButton_Volver.setBorder(null);
    jButton_Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton_Volver.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_VolverActionPerformed(evt);
          }
        });

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Nombre:");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Correo electrónico:");

    jLabel3.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("<html>Crear usuario<hr/></html>");

    jLabel4.setBackground(new java.awt.Color(255, 255, 255));
    jLabel4.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/imagenes/Loguitox90.jpg"))); // NOI18N
    jLabel4.setBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 220, 62), 2));

    txt_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    txt_nombre.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_nombreActionPerformed(evt);
          }
        });

    jButton_Ingresar.setBackground(new java.awt.Color(0, 220, 62));
    jButton_Ingresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButton_Ingresar.setForeground(new java.awt.Color(255, 255, 255));
    jButton_Ingresar.setText("Crear ");
    jButton_Ingresar.setBorder(null);
    jButton_Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton_Ingresar.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_IngresarActionPerformed(evt);
          }
        });

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Número de identificación:");

    txt_correo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    txt_correo.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_correoActionPerformed(evt);
          }
        });

    txt_identificacion1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    txt_identificacion1.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_identificacion1ActionPerformed(evt);
          }
        });

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Contraseña:");

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("Confirmar contraseña:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(153, 153, 153))
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(
                                        jButton_Volver,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(101, 101, 101)
                                    .addComponent(
                                        jLabel3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(
                                                txt_nombre,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                250,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                jLabel2,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                jLabel1,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                jLabel5,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                txt_correo,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                250,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                txt_identificacion1,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                250,
                                                Short.MAX_VALUE)
                                            .addComponent(
                                                jLabel6,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(pass_contraseña)
                                            .addComponent(
                                                jLabel7,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                            .addComponent(pass_confirmacion)
                                            .addComponent(
                                                jButton_Ingresar,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))))
                    .addContainerGap(83, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(
                        jButton_Volver,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        25,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(
                        jLabel3,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        txt_nombre,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        25,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        txt_identificacion1,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        25,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        txt_correo,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        25,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        pass_contraseña,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        25,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel7)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addComponent(
                        pass_confirmacion,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        25,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(
                        jButton_Ingresar,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        30,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                jPanel1,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                jPanel1,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void txt_nombreActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_txt_nombreActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_txt_nombreActionPerformed

  private void jButton_IngresarActionPerformed(java.awt.event.ActionEvent evt) {
    Usuario usuario;
    Gestor_Usuario gestorUsuario; // GEN-FIRST:event_jButton_IngresarActionPerformed

    String correo = txt_correo.getText();
    String contraseña = pass_contraseña.getText();

    if (MetodosGenerales.validarId(txt_identificacion1.getText())) {
      if (!MetodosGenerales.validarEmail(correo)) {
        JOptionPane.showMessageDialog(null, "Ingrese un correo válido");
      } else {
        if (!MetodosGenerales.validarContraseña(contraseña)) {
          JOptionPane.showMessageDialog(null, "Ingrese una contraseña válida");
        } else {
          gestorUsuario = new Gestor_Usuario();
          String identificacion = txt_identificacion1.getText();
          String nombre = txt_nombre.getText();
          usuario = new Usuario(identificacion, nombre, correo, contraseña);
          gestorUsuario.agregarUsuario(usuario);
          JOptionPane.showMessageDialog(null, "Usuario registrado con éxito");
          txt_identificacion1.setText("");
          txt_nombre.setText("");
          txt_correo.setText("");
          pass_contraseña.setText("");
          pass_confirmacion.setText("");
        }
      }
    } else {
      JOptionPane.showMessageDialog(null, "Ingrese un número de identificación válido");
    }
  } // GEN-LAST:event_jButton_IngresarActionPerformed

  private void jButton_VolverActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton_VolverActionPerformed

    abrirVentana(new Login_JFrame());
    this.dispose();
  } // GEN-LAST:event_jButton_VolverActionPerformed

  private void txt_correoActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_txt_correoActionPerformed
  } // GEN-LAST:event_txt_correoActionPerformed

  private void txt_identificacion1ActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_txt_identificacion1ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_txt_identificacion1ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton_Ingresar;
  private javax.swing.JButton jButton_Volver;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPasswordField pass_confirmacion;
  private javax.swing.JPasswordField pass_contraseña;
  private javax.swing.JTextField txt_correo;
  private javax.swing.JTextField txt_identificacion1;
  private javax.swing.JTextField txt_nombre;
  // End of variables declaration//GEN-END:variables
}
