package vistas;

import java.awt.Image;
import java.awt.Toolkit;

import static recursos.MetodosGenerales.abrirVentana;

public class Inicio_JFrame extends javax.swing.JFrame {

  public Inicio_JFrame() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  @Override
  public Image getIconImage() {
    return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo.jpg"));
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jButton_Sesion = new javax.swing.JButton();
    jButton_Autogestión = new javax.swing.JButton();
    jButton_Soporte = new javax.swing.JButton();
    jButton_Acercade = new javax.swing.JButton();
    jLabel_Texto = new javax.swing.JLabel();
    jLabel_Frase = new javax.swing.JLabel();
    jLabel_Fondo = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Gestión Yeralitas");
    setIconImage(getIconImage());
    setName("Inicio_JFrame"); // NOI18N
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setBackground(new java.awt.Color(255, 153, 0));
    jLabel2.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("<html>YerAlitas <hr/></html>");
    getContentPane()
        .add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 240, -1));

    jLabel3.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/imagenes/Loguito.jpg"))); // NOI18N
    jLabel3.setBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    getContentPane()
        .add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 200));

    jButton_Sesion.setBackground(new java.awt.Color(255, 116, 1));
    jButton_Sesion.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
    jButton_Sesion.setForeground(new java.awt.Color(255, 255, 255));
    jButton_Sesion.setText("Iniciar sesión");
    jButton_Sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jButton_Sesion.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_SesionActionPerformed(evt);
          }
        });
    getContentPane()
        .add(jButton_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 220, 40));

    jButton_Autogestión.setBackground(new java.awt.Color(255, 116, 1));
    jButton_Autogestión.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
    jButton_Autogestión.setForeground(new java.awt.Color(255, 255, 255));
    jButton_Autogestión.setText("Autogestión");
    jButton_Autogestión.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jButton_Autogestión.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_AutogestiónActionPerformed(evt);
          }
        });
    getContentPane()
        .add(
            jButton_Autogestión,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 220, 40));

    jButton_Soporte.setBackground(new java.awt.Color(255, 116, 1));
    jButton_Soporte.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
    jButton_Soporte.setForeground(new java.awt.Color(255, 255, 255));
    jButton_Soporte.setText("Soporte");
    jButton_Soporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jButton_Soporte.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_SoporteActionPerformed(evt);
          }
        });
    getContentPane()
        .add(jButton_Soporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 220, 40));

    jButton_Acercade.setBackground(new java.awt.Color(255, 116, 1));
    jButton_Acercade.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
    jButton_Acercade.setForeground(new java.awt.Color(255, 255, 255));
    jButton_Acercade.setText("Acerca de nosotros");
    jButton_Acercade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jButton_Acercade.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_AcercadeActionPerformed(evt);
          }
        });
    getContentPane()
        .add(
            jButton_Acercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 220, 40));

    jLabel_Texto.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
    jLabel_Texto.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Texto.setText(
        "<html>\"Bienvenido al programa oficial de Yeralitas <br/> para la gestión y administración de la empresa\"<html>");
    getContentPane()
        .add(jLabel_Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

    jLabel_Frase.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
    jLabel_Frase.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_Frase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel_Frase.setText("\"Sabor inigualable\"\n");
    getContentPane()
        .add(jLabel_Frase, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 190, -1));

    jLabel_Fondo.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo_frame.jpg"))); // NOI18N
    getContentPane()
        .add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 992, -1));

    jPanel1.setBackground(new java.awt.Color(0, 220, 62));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 992, Short.MAX_VALUE));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButton_SesionActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton_SesionActionPerformed

    abrirVentana(new Login_JFrame());
    this.dispose();
  } // GEN-LAST:event_jButton_SesionActionPerformed

  private void jButton_SoporteActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton_SoporteActionPerformed
    // TODO add your handling code here:
    abrirVentana(new Soporte_JFrame());
    this.dispose();
  } // GEN-LAST:event_jButton_SoporteActionPerformed

  private void jButton_AutogestiónActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton_AutogestiónActionPerformed
    // TODO add your handling code here:
    abrirVentana(new Autogestion_JFrame());
    this.dispose();
  } // GEN-LAST:event_jButton_AutogestiónActionPerformed

  private void jButton_AcercadeActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton_AcercadeActionPerformed
    // TODO add your handling code here:
    abrirVentana(new Acercade_JFrame());
    this.dispose();
  } // GEN-LAST:event_jButton_AcercadeActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton_Acercade;
  private javax.swing.JButton jButton_Autogestión;
  private javax.swing.JButton jButton_Sesion;
  private javax.swing.JButton jButton_Soporte;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel_Fondo;
  private javax.swing.JLabel jLabel_Frase;
  private javax.swing.JLabel jLabel_Texto;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
