package views;

import controllers.EventoAccionTabla;

import java.awt.event.ActionEvent;

import resources.Colors;

public final class ActionsPanel extends javax.swing.JPanel {

    public ActionsPanel(Consultas_JFrame consultaFrame) {
        initComponents();
        initTableEvent(consultaFrame.controller.obtenerAccionEvento());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_edit = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();

        setBackground(Colors.FONDOBOTONES);
        setBorder(javax.swing.BorderFactory.createLineBorder(Colors.LETRABOTONES, 3));

        btn_edit.setBackground(getBackground());
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_28.png"))); // NOI18N
        btn_edit.setToolTipText("Edit");
        btn_edit.setBorder(null);
        btn_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit.setPreferredSize(new java.awt.Dimension(30, 30));

        btn_save.setBackground(getBackground());
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diskette_28.png"))); // NOI18N
        btn_save.setToolTipText("Save");
        btn_save.setBorder(null);
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.setEnabled(false);
        btn_save.setPreferredSize(new java.awt.Dimension(30, 30));

        btn_delete.setBackground(getBackground());
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_28.png"))); // NOI18N
        btn_delete.setToolTipText("Edit");
        btn_delete.setBorder(null);
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.setPreferredSize(new java.awt.Dimension(30, 30));

        btn_add.setBackground(getBackground());
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_28.png"))); // NOI18N
        btn_add.setToolTipText("Add");
        btn_add.setBorder(null);
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void initTableEvent(EventoAccionTabla evento) {
        btn_edit.addActionListener((ActionEvent e) -> {
            evento.onEdit();
        });
        btn_save.addActionListener((ActionEvent e) -> {
            evento.onSave();
        });
        btn_delete.addActionListener((ActionEvent e) -> {
            evento.onDelete();
        });
        btn_add.addActionListener((ActionEvent e) -> {
            evento.onAdd();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    public javax.swing.JButton btn_edit;
    public javax.swing.JButton btn_save;
    // End of variables declaration//GEN-END:variables
}
