package views;

import java.awt.*;

import resources.Colors;
import models.GestorSesion;
import models.GestorUsuario;

import static resources.GeneralMethods.openFrame;

public class ConfigUser_JFrame extends javax.swing.JFrame {

    private final GestorSesion gestorSesion;

    public ConfigUser_JFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        gestorSesion = new GestorSesion();
        txt_identificacion.setText(GestorSesion.getSesion().getUsuario().getIdentificacion());
        txt_nombre.setText(GestorSesion.getSesion().getUsuario().getNombre());
        txt_correo.setText(GestorSesion.getSesion().getUsuario().getCorreo());
    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logox800.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_cmbContra = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_edit_ide = new javax.swing.JButton();
        btn_edit_nombre = new javax.swing.JButton();
        btn_edit_correo = new javax.swing.JButton();
        txt_identificacion = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User information");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(Colors.FONDO);

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel2.setForeground(Colors.LETRABOTONES);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Personal information<hr/></html>");

        btn_exit.setBackground(Colors.FONDO);
        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_exit.setForeground(Colors.LETRABOTONES);
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btn_exit.setToolTipText("Log out");
        btn_exit.setCursor(new java.awt.Cursor(Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        btn_exit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_exitKeyPressed(evt);
            }
        });

        btn_volver.setBackground(Colors.FONDOBOTONES);
        btn_volver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_volver.setForeground(Colors.LETRABOTONES);
        btn_volver.setText("Return");
        btn_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        btn_volver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_volverKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(Colors.LETRABOTONES);
        jLabel1.setText("Identification number:");

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setForeground(Colors.LETRABOTONES);
        jLabel4.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel6.setForeground(Colors.LETRABOTONES);
        jLabel6.setText("Name:");

        btn_cmbContra.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btn_cmbContra.setText("Change password");
        btn_cmbContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cmbContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cmbContraActionPerformed(evt);
            }
        });
        btn_cmbContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_cmbContraKeyPressed(evt);
            }
        });

        btn_modificar.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btn_modificar.setText("Save changes");
        btn_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        btn_modificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_modificarKeyPressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Loguitox200.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        btn_edit_ide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btn_edit_ide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit_ide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_ideActionPerformed(evt);
            }
        });
        btn_edit_ide.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_edit_ideKeyPressed(evt);
            }
        });

        btn_edit_nombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btn_edit_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_nombreActionPerformed(evt);
            }
        });
        btn_edit_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_edit_nombreKeyPressed(evt);
            }
        });

        btn_edit_correo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btn_edit_correo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_correoActionPerformed(evt);
            }
        });
        btn_edit_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_edit_correoKeyPressed(evt);
            }
        });

        txt_identificacion.setEditable(false);
        txt_identificacion.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txt_identificacion.setForeground(new java.awt.Color(102, 102, 102));
        txt_identificacion.setBorder(javax.swing.BorderFactory.createLineBorder(Colors.LETRABOTONES));
        txt_identificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_identificacionKeyPressed(evt);
            }
        });

        txt_nombre.setEditable(false);
        txt_nombre.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(102, 102, 102));
        txt_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(Colors.LETRABOTONES));

        txt_correo.setEditable(false);
        txt_correo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txt_correo.setForeground(new java.awt.Color(102, 102, 102));
        txt_correo.setBorder(javax.swing.BorderFactory.createLineBorder(Colors.LETRABOTONES));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exit)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cmbContra, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(215, 378, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_edit_ide))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_edit_correo))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_edit_nombre)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_volver)
                    .addComponent(btn_exit))
                .addGap(42, 42, 42)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_edit_ide, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_edit_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_edit_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)))
                .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_cmbContra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_edit_ideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_ideActionPerformed
        // TODO add your handling code here:
        txt_identificacion.setEditable(true);
    }//GEN-LAST:event_btn_edit_ideActionPerformed

    private void btn_edit_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_nombreActionPerformed
        // TODO add your handling code here:
        txt_nombre.setEditable(true);
    }//GEN-LAST:event_btn_edit_nombreActionPerformed

    private void btn_edit_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_correoActionPerformed
        // TODO add your handling code here:
        txt_correo.setEditable(true);
    }//GEN-LAST:event_btn_edit_correoActionPerformed

    private void btn_volverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_volverKeyPressed

        if (evt.getKeyCode() == 10) {
            btn_volver.doClick();
        } else if (evt.getKeyCode() == 9) {
            btn_edit_ide.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_volverKeyPressed

    private void txt_identificacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_identificacionKeyPressed
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == 9) {
            btn_edit_nombre.requestFocus();
        }     // TODO add your handling code here:
    }//GEN-LAST:event_txt_identificacionKeyPressed

    private void btn_edit_ideKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_edit_ideKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            btn_edit_ide.doClick();
        }
    }//GEN-LAST:event_btn_edit_ideKeyPressed

    private void btn_edit_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_edit_nombreKeyPressed
        if (evt.getKeyCode() == 10) {
            btn_edit_nombre.doClick();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit_nombreKeyPressed

    private void btn_edit_correoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_edit_correoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            btn_edit_correo.doClick();
        }
    }//GEN-LAST:event_btn_edit_correoKeyPressed

    private void btn_modificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_modificarKeyPressed

        if (evt.getKeyCode() == 10) {
            btn_modificar.doClick();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificarKeyPressed

    private void btn_cmbContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_cmbContraKeyPressed
        if (evt.getKeyCode() == 10) {
            btn_cmbContra.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cmbContraKeyPressed

    private void btn_exitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_exitKeyPressed
        if (evt.getKeyCode() == 10) {
            btn_exit.doClick();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btn_exitKeyPressed

    private void btn_exitActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        openFrame(new Inicio_JFrame());
        gestorSesion.cerrarSesion();
        this.dispose();
    } // GEN-LAST:event_btn_exitActionPerformed

    private void btn_volverActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        Menu_JFrame.getMenu().setVisible(true);
        this.dispose();
    } // GEN-LAST:event_btn_volverActionPerformed

    private void btn_cmbContraActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        openFrame(new ConfigContra_JFrame());
        this.dispose();
    } // GEN-LAST:event_jButton1ActionPerformed

    private void btn_modificarActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton2ActionPerformed
        GestorUsuario gestorUsuario = new GestorUsuario();
        gestorUsuario.ModificarUsuario(GestorSesion.getSesion(), txt_identificacion.getText(), txt_nombre.getText(), txt_correo.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cmbContra;
    private javax.swing.JButton btn_edit_correo;
    private javax.swing.JButton btn_edit_ide;
    private javax.swing.JButton btn_edit_nombre;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_identificacion;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
