package views;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import resources.Colors;

import static resources.GeneralMethods.openFrame;

public class Inicio_JFrame extends javax.swing.JFrame {

    public Inicio_JFrame() {
        initComponents();
        try {
            Class.forName("resources.Conexion");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Inicio_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logox800.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JButton();
        jButton_Autogestión = new javax.swing.JButton();
        jButton_Soporte = new javax.swing.JButton();
        jButton_Acercade = new javax.swing.JButton();
        jLabel_Texto = new javax.swing.JLabel();
        jLabel_Frase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión Yeralitas");
        setIconImage(getIconImage());
        setName("Inicio_JFrame"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(Colors.FONDO);
        jPanel1.setPreferredSize(new java.awt.Dimension(990, 609));

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel2.setForeground(Colors.LETRAFONDO);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>YerAlitas <hr/></html>");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Loguitox200.png"))); // NOI18N

        btn_iniciar.setBackground(Colors.FONDOBOTONES);
        btn_iniciar.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        btn_iniciar.setForeground(Colors.LETRABOTONES);
        btn_iniciar.setText("Sign in");
        btn_iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        jButton_Autogestión.setBackground(Colors.FONDOBOTONES);
        jButton_Autogestión.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jButton_Autogestión.setForeground(Colors.LETRABOTONES);
        jButton_Autogestión.setText("Self-management");
        jButton_Autogestión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Autogestión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AutogestiónActionPerformed(evt);
            }
        });

        jButton_Soporte.setBackground(btn_iniciar.getBackground());
        jButton_Soporte.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jButton_Soporte.setForeground(Colors.LETRABOTONES);
        jButton_Soporte.setText("Support");
        jButton_Soporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Soporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SoporteActionPerformed(evt);
            }
        });

        jButton_Acercade.setBackground(Colors.FONDOBOTONES);
        jButton_Acercade.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jButton_Acercade.setForeground(Colors.LETRABOTONES);
        jButton_Acercade.setText("About Yeralitas");
        jButton_Acercade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Acercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AcercadeActionPerformed(evt);
            }
        });

        jLabel_Texto.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel_Texto.setForeground(Colors.LETRAFONDO);
        jLabel_Texto.setText("<html>\"Welcome to the official Yeralitas program <br/> for the management and \nadministration <br/>  of the company information\"<html>");

        jLabel_Frase.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel_Frase.setForeground(Colors.LETRAFONDO);
        jLabel_Frase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Frase.setText("\"¡Sabor inigualable!\" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(756, 756, 756)
                            .addComponent(jButton_Acercade, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(btn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(276, 276, 276)
                            .addComponent(jButton_Autogestión, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(516, 516, 516)
                            .addComponent(jButton_Soporte, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(jLabel_Frase, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(28, 28, 28)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(186, 186, 186)
                            .addComponent(btn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(jLabel_Frase))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(75, 75, 75)
                                    .addComponent(jButton_Acercade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(186, 186, 186)
                                    .addComponent(jButton_Autogestión, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(186, 186, 186)
                                    .addComponent(jButton_Soporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(90, 90, 90)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(105, 105, 105)))
        );

        btn_iniciar.getAccessibleContext().setAccessibleParent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton_SesionActionPerformed

        openFrame(new Login_JFrame());
        this.dispose();
    } // GEN-LAST:event_jButton_SesionActionPerformed

    private void jButton_SoporteActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton_SoporteActionPerformed
        // TODO add your handling code here:
        openFrame(new Soporte_JFrame());
        this.dispose();
    } // GEN-LAST:event_jButton_SoporteActionPerformed

    private void jButton_AutogestiónActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton_AutogestiónActionPerformed
        // TODO add your handling code here:
        openFrame(new Autogestion_JFrame());
        this.dispose();
    } // GEN-LAST:event_jButton_AutogestiónActionPerformed

    private void jButton_AcercadeActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton_AcercadeActionPerformed
        // TODO add your handling code here:
        openFrame(new Acercade_JFrame());
        this.dispose();
    } // GEN-LAST:event_jButton_AcercadeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton jButton_Acercade;
    private javax.swing.JButton jButton_Autogestión;
    private javax.swing.JButton jButton_Soporte;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Frase;
    private javax.swing.JLabel jLabel_Texto;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
