package views;

import java.awt.*;

import controllers.ControladorSesion;
import resources.GeneralMethods;
import resources.Colors;

import static resources.GeneralMethods.openFrame;

public class Login_JFrame extends javax.swing.JFrame {

    public Login_JFrame() {
        initComponents();
        this.setSize(404, 544);
        this.setLocationRelativeTo(null);
        ControladorSesion loginControlador = new ControladorSesion(this);
        btn_ingresar.addActionListener(loginControlador);
    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logox800.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JButton jButton_Volver = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        pass_contrasena = new javax.swing.JPasswordField();
        btn_ingresar = new javax.swing.JButton();
        lbl_Olvido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign in");
        setIconImage(getIconImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txt_id.setFocusable(true);
        pass_contrasena.setFocusable(true);
        jPanel1.setBackground(Colors.FONDOBOTONES);

        jButton_Volver.setBackground(Colors.FONDO);
        jButton_Volver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Volver.setForeground(Colors.LETRABOTONES);
        jButton_Volver.setText("Return");
        jButton_Volver.setBorder(null);
        jButton_Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(Colors.LETRABOTONES);
        jLabel1.setText("Identification:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(Colors.LETRABOTONES);
        jLabel2.setText("Password:");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        jLabel3.setForeground(Colors.LETRABOTONES);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<HTML>Sign in<HR/></HTML>");

        jLabel4.setBackground(Colors.LETRABOTONES);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Loguitox90.png")));

        txt_id.setCursor(new java.awt.Cursor(Cursor.TEXT_CURSOR));
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idKeyReleased(evt);
            }
        });

        pass_contrasena.setCursor(new java.awt.Cursor(Cursor.TEXT_CURSOR));
        pass_contrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_contrasenaKeyPressed(evt);
            }
        });

        btn_ingresar.setBackground(Colors.FONDO);
        btn_ingresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ingresar.setForeground(Colors.LETRABOTONES);
        btn_ingresar.setText("Get into");
        btn_ingresar.setBorder(null);
        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_Olvido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Olvido.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Olvido.setText("Forgot password?");
        lbl_Olvido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Olvido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_OlvidoMouseClicked(evt);
            }
        });
        lbl_Olvido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_OlvidoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(157, 157, 157)
                                                .addComponent(jLabel4))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                        .addComponent(pass_contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                        .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_Olvido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel3)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jButton_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pass_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_Olvido)
                                .addGap(25, 25, 25)
                                .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10 || evt.getKeyCode() == 9) {
            pass_contrasena.requestFocus();
        }
    }//GEN-LAST:event_txt_idKeyReleased

    private void pass_contrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_contrasenaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            btn_ingresar.doClick();
        } else if (evt.getKeyCode() == 9) {
            lbl_Olvido.requestFocus();
        }
    }//GEN-LAST:event_pass_contrasenaKeyPressed

    private void lbl_OlvidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_OlvidoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            GeneralMethods.openFrame(new Recuperacion_JFrame());
            this.dispose();
        } else if (evt.getKeyCode() == 9) {
            btn_ingresar.requestFocus();
        }
    }//GEN-LAST:event_lbl_OlvidoKeyPressed

    private void lbl_OlvidoMouseClicked(
            java.awt.event.MouseEvent evt) { // GEN-FIRST:event_jLabel_OlvidoMouseClicked
        // TODO add your handling code here:
        GeneralMethods.openFrame(new Recuperacion_JFrame());
        this.dispose();
    } // GEN-LAST:event_jLabel_OlvidoMouseClicked

    private void formWindowClosing(
            java.awt.event.WindowEvent evt) { // GEN-FIRST:event_formWindowClosing
    } // GEN-LAST:event_formWindowClosing

    private void jButton_VolverActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton_VolverActionPerformed

        openFrame(new Inicio_JFrame());
        this.dispose();
    } // GEN-LAST:event_jButton_VolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel lbl_Olvido;
    public javax.swing.JPasswordField pass_contrasena;
    public javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
