package views;

import java.awt.Image;
import java.awt.Toolkit;
import resources.Colors;
import models.GestorSesion;
import resources.GeneralMethods;
import static resources.GeneralMethods.openFrame;

public class Menu_JFrame extends javax.swing.JFrame {

    private static Menu_JFrame menu;

    private final GestorSesion gestorSesion;

    private Menu_JFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        gestorSesion = new GestorSesion();
        lbl_usuario.setText(GeneralMethods.getStringRole() + GestorSesion.getSesion().getUsuario().getNombre());
    }

    public static Menu_JFrame getMenu() {
        return menu == null ? new Menu_JFrame() : menu;
    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logox800.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        btn_datos = new javax.swing.JButton();
        btn_inventario = new javax.swing.JButton();
        btn_tools = new javax.swing.JButton();
        btn_notas = new javax.swing.JButton();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel_Frase = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        lbl_usuario = new javax.swing.JLabel();
        btn_configuracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(Colors.FONDO);

        btn_datos.setBackground(Colors.FONDOBOTONES);
        btn_datos.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        btn_datos.setForeground(Colors.LETRABOTONES);
        btn_datos.setText("Data management");
        btn_datos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_datos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datosActionPerformed(evt);
            }
        });
        btn_datos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_datosKeyPressed(evt);
            }
        });

        btn_inventario.setBackground(Colors.FONDOBOTONES);
        btn_inventario.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        btn_inventario.setForeground(Colors.LETRABOTONES);
        btn_inventario.setText("Inventory");
        btn_inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_inventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });
        btn_inventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_inventarioKeyPressed(evt);
            }
        });

        btn_tools.setBackground(Colors.FONDOBOTONES);
        btn_tools.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        btn_tools.setForeground(Colors.LETRABOTONES);
        btn_tools.setText("Tools ");
        btn_tools.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tools.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toolsActionPerformed(evt);
            }
        });
        btn_tools.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_toolsKeyPressed(evt);
            }
        });

        btn_notas.setBackground(Colors.FONDOBOTONES);
        btn_notas.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        btn_notas.setForeground(Colors.LETRABOTONES);
        btn_notas.setText("Notes and Sales");
        btn_notas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_notas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_notasActionPerformed(evt);
            }
        });
        btn_notas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_notasKeyPressed(evt);
            }
        });

        jLabel2.setBackground(Colors.FONDO);
        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel2.setForeground(Colors.LETRAFONDO);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>YerAlitas <hr/></html>");

        jLabel_Frase.setBackground(Colors.FONDO);
        jLabel_Frase.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel_Frase.setForeground(Colors.LETRAFONDO);
        jLabel_Frase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Frase.setText("\"Unmatched flavor\"\n");

        btn_exit.setBackground(Colors.FONDO);
        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_exit.setForeground(Colors.LETRABOTONES);
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btn_exit.setToolTipText("Log out");
        btn_exit.setBorder(null);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        btn_exit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_exitKeyPressed(evt);
            }
        });

        lbl_usuario.setBackground(Colors.LETRABOTONES);
        lbl_usuario.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lbl_usuario.setForeground(Colors.LETRAFONDO);
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_usuario.setOpaque(true);

        btn_configuracion.setBackground(Colors.FONDO);
        btn_configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil.png"))); // NOI18N
        btn_configuracion.setBorder(null);
        btn_configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionActionPerformed(evt);
            }
        });
        btn_configuracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_configuracionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_exit)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tools, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_notas, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel_Frase, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_configuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Frase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tools, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_notas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    private void btn_datosKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            btn_datos.doClick();
        } else if (evt.getKeyCode() == 9) {
            btn_inventario.requestFocus();
        }
    }

    private void btn_inventarioKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            btn_inventario.doClick();
        } else if (evt.getKeyCode() == 9) {
            btn_tools.requestFocus();
        }
    }

    private void btn_toolsKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == 10) {
            btn_tools.doClick();
        } else if (evt.getKeyCode() == 9) {
            btn_notas.requestFocus();
        }        // TODO add your handling code here:
    }

    private void btn_notasKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == 10) {
            btn_notas.doClick();
        } else if (evt.getKeyCode() == 9) {
            btn_configuracion.requestFocus();
        }        // TODO add your handling code here:
    }

    private void btn_configuracionKeyPressed(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == 10) {
            btn_configuracion.doClick();
        } else if (evt.getKeyCode() == 9) {
            btn_exit.requestFocus();
        }
    }

    private void btn_exitKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == 10) {
            btn_exit.doClick();
        } else if (evt.getKeyCode() == 9) {
            btn_datos.requestFocus();
        }        // TODO add your handling code here:
    }

    private void btn_datosActionPerformed(
            java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
    }

    private void btn_inventarioActionPerformed(
            java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        GeneralMethods.openQueryFrame(1);
        this.dispose();
    }

    private void btn_toolsActionPerformed(
            java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Calculadora_JFrame.getCalculadora();
    }

    private void btn_notasActionPerformed(
            java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        openFrame(new NotVent_JFrame());
        this.dispose();
    }

    private void btn_exitActionPerformed(
            java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        openFrame(new Inicio_JFrame());
        gestorSesion.cerrarSesion();
        this.dispose();
    }

    private void btn_configuracionActionPerformed(
            java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        openFrame(new ConfigUser_JFrame());
        this.dispose();
    }
    private javax.swing.JButton btn_configuracion;
    private javax.swing.JButton btn_datos;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_inventario;
    private javax.swing.JButton btn_notas;
    private javax.swing.JButton btn_tools;
    public javax.swing.JLabel lbl_usuario;
}
