package views;

import java.awt.*;

import resources.Colors;
import resources.GeneralMethods;

import static resources.GeneralMethods.openFrame;

public class NotVent_JFrame extends javax.swing.JFrame {

    public NotVent_JFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logox800.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JButton btn_datos = new javax.swing.JButton();
        javax.swing.JButton btn_notas = new javax.swing.JButton();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JButton btn_exit = new javax.swing.JButton();
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        javax.swing.JButton btn_datos1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notes & Sales history");
        setIconImage(getIconImage());
        setName("Notas_JFrame"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(Colors.FONDO);

        btn_datos.setBackground(Colors.FONDOBOTONES);
        btn_datos.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        btn_datos.setForeground(Colors.LETRABOTONES);
        btn_datos.setText("Sales");
        btn_datos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_datos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datosActionPerformed(evt);
            }
        });

        btn_notas.setBackground(Colors.FONDOBOTONES);
        btn_notas.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        btn_notas.setForeground(Colors.LETRABOTONES);
        btn_notas.setText("Notes");
        btn_notas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_notas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_notasActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel2.setForeground(Colors.LETRABOTONES);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Sales and notes <hr/></html>");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Loguitox200.png")));

        btn_exit.setBackground(Colors.FONDO);
        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_exit.setForeground(Colors.LETRABOTONES);
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png")));
        btn_exit.setCursor(new java.awt.Cursor(Cursor.HAND_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        jButton1.setBackground(Colors.FONDOBOTONES);
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(Colors.LETRABOTONES);
        jButton1.setText("Return");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_datos1.setBackground(Colors.FONDOBOTONES);
        btn_datos1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        btn_datos1.setForeground(Colors.LETRABOTONES);
        btn_datos1.setText("Sales history");
        btn_datos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_datos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_datos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_exit)
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(158, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_datos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_notas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_datos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(115, 115, 115)
                                .addComponent(jLabel3)
                                .addGap(125, 125, 125))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_exit)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton1)))
                                .addGap(66, 66, 66)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(btn_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(btn_datos1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(btn_notas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(140, 140, 140))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_notasActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btn_notasActionPerformed
        // TODO add your handling code here:
        openFrame(new Notas_JFrame());
        this.dispose();
    } // GEN-LAST:event_btn_notasActionPerformed

    private void btn_exitActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        openFrame(new Inicio_JFrame());
        this.dispose();
    } // GEN-LAST:event_btn_exitActionPerformed

    private void jButton1ActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu_JFrame.getMenu().setVisible(true);
        this.dispose();
    } // GEN-LAST:event_jButton1ActionPerformed

    private void btn_datosActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btn_datosActionPerformed
        GeneralMethods.openQueryFrame(2);
        this.dispose();
    } // GEN-LAST:event_btn_datosActionPerformed

    private void btn_datos1ActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btn_datos1ActionPerformed
        // TODO add your handling code here:
        openFrame(new Historial_JFrame());
        this.dispose();
    }
}
