package views;

import java.awt.Image;
import java.awt.Toolkit;

import resources.Colors;

import java.time.LocalTime;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;

import models.Sesion;
import models.Usuario;
import resources.GeneralMethods;
import models.GestorUsuario;
import resources.Mail;

public class Recuperacion_JFrame extends javax.swing.JFrame {

    private final GestorUsuario gestorUsuario;
    private Optional<Usuario> optUsr;
    private String codigo;

    public Recuperacion_JFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        gestorUsuario = new GestorUsuario();
    }

    @Override
    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Logox800.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JButton jButton_Volver = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JPasswordField();
        btn_codigo = new javax.swing.JButton();
        btn_verificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password recovery");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(Colors.FONDOBOTONES);

        jButton_Volver.setBackground(Colors.FONDO);
        jButton_Volver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Volver.setForeground(Colors.LETRABOTONES);
        jButton_Volver.setText("Return");
        jButton_Volver.setBorder(null);
        jButton_Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(Colors.LETRABOTONES);
        jLabel1.setText("Email:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(Colors.LETRABOTONES);
        jLabel2.setText("Code:");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        jLabel3.setForeground(Colors.LETRABOTONES);
        jLabel3.setText("<html>Recover password<hr/></html>");

        jLabel4.setBackground(Colors.LETRABOTONES);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Loguitox90.png")));

        txt_correo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_correoKeyPressed(evt);
            }
        });

        txt_codigo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoKeyPressed(evt);
            }
        });

        btn_codigo.setBackground(Colors.FONDO);
        btn_codigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_codigo.setForeground(Colors.LETRABOTONES);
        btn_codigo.setText("Sent code");
        btn_codigo.setBorder(null);
        btn_codigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_codigoActionPerformed(evt);
            }
        });
        btn_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_codigoKeyPressed(evt);
            }
        });

        btn_verificar.setBackground(Colors.FONDO);
        btn_verificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_verificar.setForeground(Colors.LETRABOTONES);
        btn_verificar.setText("Verify");
        btn_verificar.setBorder(null);
        btn_verificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verificarActionPerformed(evt);
            }
        });
        btn_verificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_verificarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(151, 151, 151))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jButton_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_correo, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                        .addComponent(txt_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                        .addComponent(btn_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btn_verificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    private void txt_correoKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            btn_codigo.doClick();
        } else if (evt.getKeyCode() == 9) {
            btn_codigo.requestFocus();
        }
    }

    private void btn_codigoKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            btn_codigo.doClick();
        } else if (evt.getKeyCode() == 9) {
            txt_codigo.requestFocus();
        }
    }

    private void txt_codigoKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == 10) {
            btn_verificar.doClick();
        } else if (evt.getKeyCode() == 9) {
            btn_verificar.requestFocus();
        }        // TODO add your handling code here:
    }

    private void btn_verificarKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == 10) {
            btn_verificar.doClick();
        }      // TODO add your handling code here:
    }

    private void btn_codigoActionPerformed(
            java.awt.event.ActionEvent evt) {
        String correo = txt_correo.getText();
        optUsr = gestorUsuario.obtenerByCorreo(correo);
        if (GeneralMethods.validateEmail(correo) && optUsr.isPresent()) {
            codigo = Integer.toString((int) Math.round(Math.random() * 1000000));
            Mail m = new Mail();
            try {
                m.enviarEmail(
                        "Password recovery",
                        "The code to recover your password is: " + codigo,
                        correo);
                JOptionPane.showMessageDialog(null, "Code sent");
            } catch (MessagingException ex) {
                Logger.getLogger(Recuperacion_JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Email incorrect");
        }
    }

    private void btn_returnActionPerformed(
            java.awt.event.ActionEvent evt) {
        Login_JFrame sesion = new Login_JFrame();
        sesion.setVisible(true);
        this.dispose();
    }

    private void btn_verificarActionPerformed(
            java.awt.event.ActionEvent evt) {
        String entrada = txt_codigo.getText();
        if (entrada.equals(codigo)) {
            Sesion sesion = new Sesion(optUsr.get(), LocalTime.now());
            CambioContra_JFrame contra = new CambioContra_JFrame(sesion);
            contra.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect code");
        }
    }

    private javax.swing.JButton btn_codigo;
    private javax.swing.JButton btn_verificar;
    private javax.swing.JPasswordField txt_codigo;
    private javax.swing.JTextField txt_correo;
    // End of variables declaration                   
}
